# #Adding, removing, and sorting elements

In [1]:
import numpy as np


In [8]:
arr = np.array([111,2,344,4,5,6,75,9])
arr
np.sort(arr)


array([  2,   4,   5,   6,   9,  75, 111, 344])

In [9]:
a = np.array([2,4,6,8])
b = np.array([10,12,14,16])
np.concatenate((a,b))

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2]])
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [1, 2]])