## Indexing and slicing

In [1]:
import numpy as np

In [18]:
data = np.array([4,5,6])
print(data[1:])
print(data[-2:])

[5 6]
[5 6]


In [23]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a <= 5])
print(a[a >= 5])
print(a[a%2==0])

[1 2 3 4 5]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [26]:
b = np.nonzero(a > 5)
b

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [27]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


# #create an array from existing data

In [28]:
ex = np.array([1,2,3,4,5,6,7,8,9,10])
ex

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
ar2 = ex[-1::-1]
print(ar2)

[10  9  8  7  6  5  4  3  2  1]


In [54]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))



[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [65]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3[0:1] = 0
a3

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a3.sum(axis=0)

array([11, 13, 15])

In [69]:
a3.sum(axis=1)

array([ 0, 15, 24])