# Broadcasting

In [27]:
import numpy as np
from numpy import random

In [2]:
b =2
b1 = np.array([1,2,3,4,5,6,7,8,9,10])
b1 * b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
b1.sum()

55

In [4]:
b1.max()

10

In [5]:
b1.min()

1

In [10]:
print(b1.sum(axis=0))


55


In [18]:
b3 = np.ones((8,3,2)) # Number of list, Number of columns, Number of rows
b3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# Generating random numbers

In [36]:
b4 = random.randint(100)
b4

8

In [37]:
# Unique
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]
