# Transposing and reshaping a matrix

In [1]:
import numpy as np

In [17]:

data = np.arange(20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
data.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [25]:
data.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Reversing arrays

In [26]:
reversedarr = np.flip(data)
print(reversedarr)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [30]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np.flip(arr_2d))
print(np.flip(arr_2d, axis=0))

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


#  flattening multidimensional arrays

In [33]:
fl = np.array([[10,20,30],[40,50,70],[80,90,100]])
fl.flatten()

array([ 10,  20,  30,  40,  50,  70,  80,  90, 100])

In [37]:
f2 = fl.ravel()
fl[0] = 98
print(fl)

[[ 98  98  98]
 [ 40  50  70]
 [ 80  90 100]]
